import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import { useState } from "react";
import { getGeminiResponse } from "../services/geminiAPI";
import { useNavigate } from "react-router-dom";
import { jsPDF } from "jspdf";
import { auth } from "../services/firebase";
import { savePitchToFirestore } from "../services/firebase";

export default function Text() {
  const [text, setText] = useState("");
  const [output, setOutput] = useState("");
  const [loading, setLoading] = useState(false);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const navigate = useNavigate();

  const handleGenerate = async () => {
    if (!text.trim()) return;
    setLoading(true);
    setOutput("");

    try {
      const response = await getGeminiResponse(text);
      setOutput(response);
      
      const userId = auth.currentUser?.uid;
      if (userId) {
        await savePitchToFirestore(userId, text, response);
      }
      
    } catch (error) {
      console.error("Gemini API error:", error);
      setOutput("⚠️ Failed to generate response. Please try again later.");
    } finally {
      setLoading(false);
    }
  };

  const generatePDF = () => {
    const doc = new jsPDF();
    
    doc.setFillColor(30, 41, 59);
    doc.rect(0, 0, 210, 297, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.text("Startup Pitch Deck", 20, 30);
    
    doc.setFontSize(12);
    doc.setTextColor(165, 180, 252);
    doc.text("Generated by PitchCraft AI", 20, 40);
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.text("Your Idea:", 20, 60);
    doc.setFontSize(10);
    const splitText = doc.splitTextToSize(text, 170);
    doc.text(splitText, 20, 70);
    
    if (output) {
      doc.setFontSize(14);
      doc.setTextColor(255, 255, 255);
      doc.text("Generated Pitch:", 20, 100);
      doc.setFontSize(10);
      const splitOutput = doc.splitTextToSize(output, 170);
      doc.text(splitOutput, 20, 110);
    }
    
    doc.save("pitchcraft-pitch.pdf");
  };

  return (
    <div className="flex min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 text-gray-100">
      {/* Sidebar - Mobile: conditional, Desktop: visible */}
      <div className="hidden md:block">
        <Sidebar />
      </div>
      
      {/* Mobile Sidebar - Hamburger click par show hoga */}
      {isSidebarOpen && (
        <div className="fixed inset-0 z-40 md:hidden">
          <Sidebar onClose={() => setIsSidebarOpen(false)} />
          {/* Overlay click par sidebar band ho jayega */}
          <div 
            className="fixed inset-0 bg-black bg-opacity-50 z-30"
            onClick={() => setIsSidebarOpen(false)}
          ></div>
        </div>
      )}

      {/* Main Area */}
      <div className="flex flex-col flex-1 md:ml-64">
        {/* Navbar with hamburger function */}
        <Navbar onMenuToggle={setIsSidebarOpen} />

        {/* Text Editor Section */}
        <main className="flex-1 p-4 md:p-8 overflow-y-auto flex flex-col gap-4 md:gap-6 pt-20 md:pt-16">
          <div className="flex flex-col md:flex-row md:items-center md:justify-between">
            <h2 className="text-xl md:text-2xl font-bold text-indigo-400 mb-4 md:mb-6">
              Write or paste your text below
            </h2>
            <button
              onClick={() => navigate('/dashboard')}
              className="px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded-lg font-semibold transition mb-4 md:mb-0"
            >
              ← Back to Dashboard
            </button>
          </div>

          {/* Input box */}
          <div className="bg-gray-800/70 border border-gray-700 rounded-xl md:rounded-2xl p-4 md:p-6 shadow-xl backdrop-blur-lg">
            <textarea
              value={text}
              onChange={(e) => setText(e.target.value)}
              placeholder="Start typing your pitch, script, or idea..."
              className="w-full h-32 md:h-40 bg-transparent outline-none text-gray-100 resize-none placeholder-gray-500 border border-gray-600 rounded-lg p-3"
            ></textarea>

            <button
              onClick={handleGenerate}
              disabled={loading}
              className="mt-4 w-full md:w-auto px-6 py-3 rounded-xl bg-indigo-500 hover:bg-indigo-600 text-white font-semibold transition-all shadow-lg hover:shadow-indigo-700/30 disabled:opacity-60"
            >
              {loading ? "Generating..." : "Generate Result"}
            </button>
          </div>

          {/* Output box */}
          {output && (
            <div className="bg-gray-800/80 border border-gray-700 rounded-xl md:rounded-2xl p-4 md:p-6 shadow-lg">
              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-4">
                <h3 className="text-lg font-semibold text-indigo-400 mb-2 sm:mb-0">
                  Output:
                </h3>
                <button
                  onClick={generatePDF}
                  className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg font-semibold transition shadow-lg"
                >
                  Download PDF
                </button>
              </div>
              <p className="text-gray-200 whitespace-pre-line">{output}</p>
            </div>
          )}
        </main>
      </div>
    </div>
  );
}